name: Test CWL

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  list-tests:
    runs-on: ubuntu-latest
    outputs:
      tests-matrix: ${{ steps.set-matrix.outputs.tests-matrix }}
    steps:
    - uses: actions/checkout@v3
    - id: set-matrix
      run: |
        echo "tests-matrix=$(ls tests/*.cwl | jq -R -s -c 'split("\n")[:-1] | map([., (sub("\\.cwl$"; ".yml"))])')"  >> "$GITHUB_OUTPUT"
    - name: Show matrix
      run: |
        echo ${{ steps.set-matrix.outputs.tests-matrix }}
  test-cwl:
    needs: list-tests
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest]
          tests: ${{ fromJson(needs.list-tests.outputs.tests-matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Python
      run: |
        echo "# Install cwltool" >> $GITHUB_STEP_SUMMARY
        pip install cwltool
    - name: Setup Docker
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        echo "# Install docker on mac-runner" >> $GITHUB_STEP_SUMMARY
        brew install docker
    - name: Get CWL Version
      run: |
        echo "# cwl version is $(cwltool --version) " >> $GITHUB_STEP_SUMMARY
    - name: Get Docker Version
      run: |
        echo "# docker version is $(docker --version) " >> $GITHUB_STEP_SUMMARY
    - name: Run CWL
      run: |
        echo "# Run test ${{ matrix.tests[0] }} " >> $GITHUB_STEP_SUMMARY
        echo cwltool --verbose --docker ${{ matrix.tests[0] }} --input ${{ matrix.tests[1] }}