name: Pull and Test Singularity Image
on:
  workflow_run:
    workflows: [Build and Push Docker Image]
    types:
      - completed
jobs:
  test-singularity:
    runs-on: ubuntu-latest
    steps:
      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.6.4
      - name: Pull Singularity image
        run: singularity pull docker://ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest
