name: Pull and Test Singularity Image
on:
  workflow_run:
    workflows: [Build and Push Docker Image]
    types: [completed]
  workflow_dispatch:
jobs:
  test-singularity:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: get-name
        run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
          echo "REPO_OWNER=$(echo ${{ github.repository_owner}} | tr '[:upper:]' '[:lower:]' )" >> $GITHUB_ENV
      - name: print-name
        run: |
          echo "${{ env.REPO_NAME }}"
          echo "${{ env.REPO_OWNER }}"
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: myenv
      - name: Install Dependencies
        run: |
          conda install -c conda-forge -y singularity
          conda info
          which singularity
          singularity --version
      - name: Pull Singularity image
        run: |
          singularity pull docker://ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest