name: Pull and Test Singularity Image
on:
  workflow_run:
    workflows: [Build and Push Docker Image]
    types: [completed]
  workflow_dispatch:
jobs:
  test-singularity:
    runs-on: ubuntu-latest
    steps:
      - name: get-name
        run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
          echo "REPO_OWNER=$(echo ${{ github.repository_owner}} | tr '[:upper:]' '[:lower:]' )" >> $GITHUB_ENV
      - name: print-name
        run: |
          echo "${{ env.REPO_NAME }}"
          echo "${{ env.REPO_OWNER }}"
      - name: get conda
        run: |
          echo $(which conda)
          echo $CONDA
      - name: Create Conda Env
        run: conda create -n test-singularity python=3.9 -y 
      - name: Activate Conda
        run: $CONDA/bin/activate test-singularity
      - name: Install Dependencies
        run: |
          conda install -c conda-forge -y singularity
          whereis singularity
      - name: Pull Singularity image
        run: singularity pull docker://ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest