name: Pull and Test Singularity Image
on:
  workflow_run:
    workflows: [Build and Push Docker Image]
    types: [completed]
jobs:
  test-singularity:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          conda install -c conda-forge -y singularity
      - name: Pull Singularity image
        run: singularity pull docker://ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest